<section class="content-header">
    <h1><i class='fas fa-users mr-1'></i> Usuarios <small>Eliminados</small></h1>
    <ol class="breadcrumb">
        <li><a class="text-primary" href="[URL_BASE]usuarios/activos">Activos</a></li>
		<li><a class="text-secondary" href="[URL_BASE]usuarios/noactivos">No Activos</a></li>
		<li><a class="active text-danger" href="#">Eliminados</a></li>
		<li><a class="text-info" href="[URL_BASE]usuarios/nuevo">Nuevo Usuario</a></li>
        <li><a href="#">[FECHA]</a></li>
    </ol>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-danger">
		<div class="box-header">
			<h3 class="box-title"><span class="small mt-1" id="leyenda">[LEYENDA]</span></h3>
		</div>
		<div class="box-body">
            <div class="row">
                <div class="col-12 col-md-8 mb-2">
                    <select class="form control form-control-sm" id="limite" style="width: auto;">
                        <option value="10">10</option>
                        <option value="25" selected>25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <button type="button" class="btn btn-sm btn-outline-primary" id="btn-print">Print</button>
                    <a href="[URL_BASE]usuarios/exportar/pdf" class="btn btn-sm btn-outline-primary" id="btn-pdf">PDF</a>
                    <a href="[URL_BASE]usuarios/exportar/excel" class="btn btn-sm btn-outline-primary" id="btn-xls">Excel</a>
                    <button type="button" class="btn btn-sm btn-outline-primary" id="btn-word">Word</button>
                    <a href="[URL_BASE]usuarios/exportar/csv" class="btn btn-sm btn-outline-primary" id="btn-csv">CSV</a>
                </div>
                <div class="col-12 col-md-4 mb-2">
                    <div class="input-group input-group-sm my-1" id="cabecera">
                        <input type="hidden" value="[TOKEN]" id="token">
                        <input type="hidden" value="1" id="pagina">
                        <input type="hidden" value="ASC" id="orden">
					    <input type="hidden" value="u.id" id="campo">
                        <input class="form-control form-control-sm" type="text" id="search" placeholder="Buscador">
                        <div class="input-group-append">
                            <button class="btn btn-sm btn-outline-info question-mark float-right" type="button" title="Buscador.|Se realiza una búsqueda en la base de datos que coincida con un <b>Usuario</b>, un <b>Email</b> o un <b>RUT</b>"><i class="fas fa-question"></i></button>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-hover custom-table" id="lista-usuarios">
                            <thead>
                                <tr class="small" id="columnas">
                                    <th class=""><i class='fas fa-sort mr-1' data-orden='ASC' data-campo='u.id'></i> #</th>
                                    <th class=""><i class='fas fa-sort mr-1' data-orden='ASC' data-campo='p.alias'></i> Usuario</th>
                                    <th class=""><i class='fas fa-sort mr-1' data-orden='ASC' data-campo='nombres'></i> Nombres</th>
                                    <th class=""><i class='fas fa-sort mr-1' data-orden='ASC' data-campo='u.email'></i> E-mail</th>
                                    <th class="" width="100px">RUT</th>
                                    <th class="">Teléfono</th>
                                    <th class=""><i class='fas fa-sort mr-1' data-orden='ASC' data-campo='cargo'></i> Cargo</th>
                                    <th class="">Opciones</th>
                                </tr>
                            </thead>
                            <tbody id="datos">
                                [TBODY]
                            </tbody>
                        </table>
                    </div>
                    <div class="my-1 d-flex justify-content-center" id="paginacion">[PAGINACION]</div>
                </div>
            </div>
		</div>
	</div>
</section>
<!-- Modal Ver -->
<div class="modal fade" id="modal-ver" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Información del Usuario</h5>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer">
			<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>