<table cellspacing="0" cellpadding="0" style="min-width: 600px;">
	<tr>
		<td colspan="2" style="padding: 10px; text-align: center;"><img src="[RUTA_IMG]" width="50%" height="100"></td>
	</tr>
	<tr style="background-color: blue; color: white;">
		<td style="padding: 5px; width: 40%;">Asunto:</td>
		<td style="padding: 5px; width: 60%;"><b>[ASUNTO]</b></td></td>
	</tr>
	<tr>
		<td style="padding: 5px; width: 40%;">Nombre </td>
		<td style="padding: 5px; width: 60%;">[NOMBRE]</td>
	</tr>
	<tr>
		<td style="padding: 5px; width: 40%;">Correo </td>
		<td style="padding: 5px; width: 60%;">[CORREO]</td>
	</tr>
	<tr>
		<td style="padding: 5px; width: 40%;">Mensaje</td>
		<td style="padding: 5px; width: 60%; font-size: 12px;">[MENSAJE]</td>
	</tr>
	<tr>
		<td colspan="2" style="padding: 5px;">[ENVIADO_POR]</td>
	</tr>
	<tr style="background-color: blue; color: white; font-size: 12px;">
		<td style="padding: 5px; width: 40%;">Enviado el </td>
		<td style="padding: 5px; width: 60%;">[FECHA]</td>
	</tr>
</table>