<section class="content-header">
	<h1><i class="fas fa-users fa-xs"></i> Usuarios <small>Revisar</small></h1>
	<ol class="breadcrumb mt-1">
		<?php if ( $this->_acl->accesoVista('admin_acces') ): ?>
		<li><a class="text-info" href="[URL_BASE]usuarios/activos">Activos</a></li>
		<li><a class="text-info" href="[URL_BASE]usuarios/noactivos">No Activos</a></li>
		<li><a class="text-danger" href="[URL_BASE]usuarios/eliminados">Eliminados</a></li>
		<li><a class="text-primary" href="[URL_BASE]usuarios/nuevo">Nuevo Usuario</a></li>
		<?php endif; ?>
		<li><a>[FECHA]</a></li>
	</ol>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-body">
            <div class='alert alert-[ALERT_TIPO] alert-dismissible small mb-2 fade show' role='alert'>
                [ALERT_MENSAJE]
                <button type='button' class='close' data-dismiss='alert' aria-label='Cerrar'>
                    <span aria-hidden='true'>&times;</span>
                </button>
            </div>
            <fieldset class="scheduler-border p-2 mb-2">
                <legend class="w-auto px-2">Sistema</legend>
                <div class="row">
                    <div class="col-12 col-lg-6">
                        <div class="form-group custom-group">
                            <label class="small" for="role">Cambiar Rol</label>
                            <div class="input-group input-group-sm">
                                <select class="form-control form-control-sm" id="roles" [ROL_DISABLED]>
                                    [ROLES]
                                </select>
                            </div>
                            <small class="text-muted" id="estado_rol" >[ESTADO_ROL]</small>
                        </div>
                    </div>
                    <div class="col-12 col-lg-6">
                        <div class="form-group custom-group">
                            <label class="small" for="role">Cambiar Clave</label>
                            <div class="input-group input-group-sm">
                                <input type="password" class="form-control" id="password">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-info" type="button" id="generar">Generar</button>
                                </div>
                            </div>
                            <small class="text-muted" id="cambiar_clave"></small>
                        </div>
                    </div>
                    <div class="col-12 col-lg-6">
                        <div class="form-group custom-group">
                            <label class="" for="activado">Activar Usuario </label>
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" id="activado" value="[ACTIVADO]" [CHECK_STATE]>
                                    <small id="estado_usuario">[ESTADO_ACTIVO]</small> 
                                </label>
                            </div>
                        </div>
                        <div class="d-flex">
                            <button class="btn btn-sm btn-block btn-primary mr-2" type="button" id="guardar">Guardar Cambios</button>
                            <a class="btn btn-sm btn-warning mr-2" href="[URL_BASE]usuarios/activos">Cancelar</a>
                        </div>
                        <ul class="list-group m-2" id="mensajes"></ul>
                    </div>
                    <div class="col-12 col-lg-6">
                        <div class="form-group">
                            <input type="hidden" id="usuario_id" value="[ID]">
                            <input type="hidden" id="estado_actual" value="[ACTIVADO]">
                            <input type="hidden" id="rol_actual" value="[ROL_ACTUAL]">
                            <input type="hidden" id="token" value="[TOKEN]">
                            <div class="d-flex justify-content-between mb-2">
                                <div class="form-check form-check-inline">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" id="link_activacion">
                                        <small>Link de Activación</small> 
                                    </label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" id="envio_correo">
                                        <small>Envio Correo</small> 
                                    </label>
                                </div>
                            </div>
                            <div class="form-group custom-group" id="sendMessage" style="display: none;">
                                <label for="adicional">Enviar un mensaje (opcional)</label>
                                <textarea class="form-control form-group-sm" name="adicional" id="adicional" placeholder="Escribe un mensaje"></textarea>
                                <span class="small text-info" id="labelMessage">El mensaje sera enviado a <b>[EMAIL]</b></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-6">
                        <div class="form-group my-2">
                            <div class="mt-2 small" id="alert-sistema" style="display:none;"></div>
                        </div>
                    </div>
                </div>
            </fieldset>
		</div>
	</div>
</section>