<div class="container">
	<div class="row h-100 align-items-center justify-content-center text-center">
		<div class="col-12">
			<img class="mb-2" src="[VISTA_IMG]blockpc2.png" alt="[TITULO] blockpc.cl" width="72" height="72">
			<h2 class="text-white mt-0">[ESTADO_CUENTA]</h2>
			<hr class="divider my-4">
			<p><a class="text-white-50 mb-4 [CLASE]" href="[URL_LOGIN]" title="Login Usuario">Ir al login</a></p>
		</div>
	</div>
</div>
