<section class="content-header">
    <h1><i class='fas fa-users mr-1'></i> Usuario <small>Nuevo</small></h1>
    <ol class="breadcrumb">
        <li><a class="text-primary" href="[URL_BASE]usuarios/activos">Activos</a></li>
		<li><a class="text-secondary" href="[URL_BASE]usuarios/noactivos">No Activos</a></li>
		<li><a class="text-danger" href="[URL_BASE]usuarios/eliminados">Eliminados</a></li>
		<li><a class="active text-info" href="#">Nuevo Usuario</a></li>
        <li><a href="#">[FECHA]</a></li>
    </ol>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
    <div class="box box-info">
        <div class="box-body">
            <form class="small" method="post" action="" id="formNuevoUsuario" autocomplete="off">
                <input type="hidden" name="token" id="token" value="[TOKEN]">
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Usuario <small>(Obligatorio)</small></legend>
                    <div class="form-row">
                        <div class="col-12 col-md-6 mb-1 custom-group">
                            <label for="alias">Usuario</label>
                            <input type="text" name="alias" id="alias" class="form-control form-control-sm" value="[ALIAS]" placeholder="Usuario">
                        </div>
                        <div class="col-12 col-md-6 mb-1 custom-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" id="email" class="form-control form-control-sm" value="[EMAIL]" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6 mb-1 custom-group">
                            <label for="clave">Clave</label>
                            <input type="password" name="clave" id="clave" class="form-control form-control-sm" value="" placeholder="Password" autocomplete="new-password">
                        </div>
                        <div class="col-12 col-md-6 mb-1 custom-group">
                            <label for="repetir">Repetir Clave</label>
                            <div class="input-group">
                                <input type="password" class="form-control form-control-sm" placeholder="Confirmar Password" name="repetir" id="repetir" autocomplete="new-password">
                                <div class="input-group-append">
                                    <button class="btn btn-sm btn-primary" type="button" id="generarClave">Generar</button>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <small id="errorGeneraClave" class="form-text text-primary mt-1"></small>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Perfil <small>(Opcional)</small></legend>
                    <div class="form-row">
                        <div class="col-12 col-md-4 mb-1 custom-group">
                            <label for="nombre">Nombres</label>
                            <input type="text" name="nombre" id="nombre" class="form-control form-control-sm" value="[NOMBRE]" placeholder="Nombres">
                        </div>
                        <div class="col-12 col-md-4 mb-1 custom-group">
                            <label for="apellido">Apellidos</label>
                            <input type="text" name="apellido" id="apellido" class="form-control form-control-sm" value="[APELLIDO]" placeholder="Apellidos">
                        </div>
                        <div class="col-12 col-md-4 mb-1 custom-group">
                            <label for="rut">RUT</label>
                            <input type="text" name="rut" id="rut" class="form-control form-control-sm" value="[RUT]" placeholder="RUT">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6 mb-1 custom-group">
                            <label for="telefono">Teléfono</label>
                            <input type="text" name="telefono" id="telefono" class="form-control form-control-sm" value="[TELEFONO]" placeholder="Teléfono">
                        </div>
                        <div class="col-12 col-md-6 mb-1 custom-group">
                            <label for="celular">Celular</label>
                            <input type="text" name="celular" id="celular" class="form-control form-control-sm" value="[CELULAR]" placeholder="Celular">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 mb-1 custom-group">
                            <label for="direccion">Dirección</label>
                            <input type="text" name="direccion" id="direccion" class="form-control form-control-sm" value="[DIRECCION]" placeholder="Dirección">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-4 mb-1 custom-group">
                            <label for="region">Región</label>
                            <select class="form-control form-control-sm" name="region" id="region">[REGIONES]</select>
                        </div>
                        <div class="col-12 col-md-4 mb-1 custom-group">
                            <label for="provincia">Provincia</label>
                            <select class="form-control form-control-sm" name="provincia" id="provincia">[PROVINCIAS]</select>
                        </div>
                        <div class="col-12 col-md-4 mb-1 custom-group">
                            <label for="comuna">Comuna</label>
                            <select class="form-control form-control-sm" name="comuna" id="comuna">[COMUNAS]</select>
                        </div>
                    </div>
                </fieldset>
                <div class="form-row">
                    <div class="col-12 col-md-6 mb-1 d-flex">
                        <button type="submit" class="btn btn-sm btn-success btn-block mr-2">Crear Usuario</button>
                        <a href="[URL_BASE]usuarios/activos" class="btn btn-md btn-warning">Cancelar</a>
                    </div>
                    <div class="col-12 col-md-6 mb-1">
                        <button type="button" class="btn btn-sm btn-success float-right" id="fakeUser">Generar Usuario</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>