<!-- Main content -->
<div class="container h-100 pt-2">
	<div class="row h-100 align-items-center justify-content-center text-center">
		<div class="col-12 align-items-center justify-content-center text-center">
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
				<p class="h4"><i class="icon fa fa-exclamation-triangle"></i> [TITULO_ERROR]</p>
				<p>[MENSAJE_ERROR]</p>
			</div>
		</div>
	</div>
</div>
