<!doctype html>
<html lang="es" class="h-100">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="[RUTA_IMG]favicon.ico">
	<title>[TITULO] | [APP_NAME]</title>
	<!-- Theme CSS - Includes Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link href="[RUTA_CSS]font-awesome.min.css" rel="stylesheet">
	<link href="[RUTA_CSS]agate.css" rel="stylesheet">
	<link href="[RUTA_CSS]frontend.css" rel="stylesheet">
	<!-- Archivos CSS: para esta vista -->
	[VISTA_CSS]
</head>
<body class="d-flex flex-column h-100">
<header>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark" id="mainNav">
		<div class="container">
			<a class="navbar-brand js-scroll-trigger" href="[URL_BASE]">[APP_NAME]</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto my-2 my-lg-0">
				[MENU_PLANTILLA]
				</ul>
			</div>
		</div>
	</nav>
</header>
<main role="main" class="flex-shrink-0">
	<div class="container-fluid">
		<div class="row"><div class="col-12">[ERROR][MENSAJE]</div></div>
	</div>
