</main>
<footer class="footer mt-auto pt-3">
	<div class="container">
		<div class="blockpc text-center">© 2019 <span><a href="https://www.blockpc.cl" target="_blank">www.blockpc.cl</a></span></div>
	</div>
</footer>
<!-- Custom scripts for this template -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="[RUTA_JS]highlight.js"></script>
<script src="[RUTA_JS]initHighlightingOnLoad.js"></script>
<script src="[RUTA_JS]frontend.js"></script>
<!-- Archivos JS: para esta vista -->
[VISTA_JS]
</body>
</html>