<nav class="" aria-label="Page navigation">
	<ul class="pagination pagination-sm">
		<li class="page-item [NO_PRIMERO]"><a class="page-link [TABLA]" href="[PRIMERO]" data-pagina="[REGISTRO_PRIMERO]">Primero</a></li>
		<li class="page-item [NO_ANTERIOR]">
			<a class="page-link [TABLA]" href="[ANTERIOR]" aria-label="Anterior" data-pagina="[REGISTRO_ANTERIOR]">
				<span aria-hidden="true">&laquo;</span>
			</a>
		</li>
		[BOTONERA]
		<li class="page-item [NO_SIGUIENTE]">
			<a class="page-link [TABLA]" href="[SIGUIENTE]" aria-label="Siguiente" data-pagina="[REGISTRO_SIGUIENTE]">
				<span aria-hidden="true">&raquo;</span>
			</a>
		</li>
		<li class="page-item [NO_ULTIMO]"><a class="page-link [TABLA]" href="[ULTIMO]" data-pagina="[REGISTRO_ULTIMO]">Último</a></li>
	</ul>
</nav>