<section class="content-header">
    <h1><i class='fas fa-cogs mr-1'></i> Rol <small>Eliminar</small></h1>
    <ol class="breadcrumb">
		<li><a class="active text-danger" href="#">Eliminar</a></li>
		<li><a class="text-primary" href="[URL_BASE]usuarios/roles/listar">Listado</a></li>
		<?php if ( $this->_acl->accesoVista("admin_acces") ) : ?>
		<li><a class="text-info" href="[URL_BASE]usuarios/roles/nuevo">Nuevo Rol</a></li>
        <?php endif; ?>
        <li><a href="#">[FECHA]</a></li>
	</ol>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-danger">
		<div class="box-body">
			<div class="row">
				<div class="col">
					<form method="post" id="nuevoRole">
						<div class="form-group custom-group">
                            <label for="role">Nombre Rol</label>
							<input type="text" id="role" class="form-control form-control-sm" placeholder="Nombre del Rol"value="[ROLE]" disabled>
						</div>
						<div class="form-group custom-group">
                            <label for="descripcion">Descripción </label>
							<textarea class="form-control form-control-sm" id="descripcion" placeholder="Descripción del Rol" disabled>[DESCRIPCION]</textarea>
						</div>
						<div class="form-group custom-group">
							<label>Editable</label>
							<div class="input-group">
								<div class="input-group-addon">
									<input type="checkbox" id="editable" [CHECK] disabled>
                                    <label class="small" for="editable">Check para hacer el rol editable</label>
								</div>
							</div>
						</div>
						<?php if ( $this->_acl->accesoVista("admin_acces") ) : ?>
						<div class="d-flex pb-2">
							<input type="hidden" name="token" id="token" value="[TOKEN]">
							<input type="hidden" name="id" id="id" value="[ID]">
							<button type="submit" class="btn btn-danger btn-sm btn-block mr-2">Eliminar Role</button>
							<a href="[URL_BASE]usuarios/roles/listar" class="btn btn-warning btn-sm">Cancelar</a>
						</div>
						<?php endif; ?>
					</form>
				</div>
				<div class="col">
					<ul class="list-group">
						<li class="list-group-item list-group-item-danger"><small>Los roles, o grupos de usuarios, se usan en listas de control de acceso (ACL) para especificar quién puede acceder a un recurso especifico según sean sus permisos.<br>Existen tres roles que el sistema trae por defecto que son: <b>SuperAdministrador</b>, <b>Administrador</b> y <b>Usuario</b>. Estos roles no se pueden editar<br>Un <b>Role</b> editable es aquel al que se le puede editar el nombre una vez creado y es la opción recomendada ante la creación de nuevos <b>Roles</b></small></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>