<section class="content-header">
    <div class="topnav" id="myTopnav">
		<a class="first">[ICONO] [TITULO]</a>
		<a href="javascript:void(0);" class="icon" onclick="myFunction()">
			<i class="fa fa-bars"></i>
		</a>
		<a class="last float-right d-none d-sm-block"><small>[FECHA]</small></a>
	</div>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-body">
		</div>
	</div>
</section>