<section class="content-header">
    <h1><i class='fas fa-cogs mr-1'></i> Permisos <small>Eliminar</small></h1>
    <ol class="breadcrumb">
		<li><a class="active text-danger" href="#">Eliminar</a></li>
		<li><a class="text-primary" href="[URL_BASE]usuarios/permisos/listar">Listado</a></li>
		<?php if ( $this->_acl->accesoVista("admin_acces") ) : ?>
		<li><a class="text-info" href="[URL_BASE]usuarios/permisos/nuevo">Nuevo Permiso</a></li>
        <?php endif; ?>
        <li><a href="#">[FECHA]</a></li>
	</ol>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-danger">
		<div class="box-body">
			<div class="row">
				<div class="col">
					<form method="post" id="nuevoPermiso">
						<div class="form-group custom-group">
							<label for="permiso">Permiso </label>
							<input type="text" id="permiso" class="form-control form-control-sm" placeholder="Nombre del Permiso"value="[PERMISO]" disabled>
						</div>
						<div class="form-group custom-group">
                            <label for="llave">Llave </label>
							<input type="text" id="llave" class="form-control form-control-sm" placeholder="EJ: llave_access" value="[LLAVE]" disabled>
						</div>
						<div class="form-group custom-group">
                            <label for="descripcion">Descripción </label>
							<textarea class="form-control form-control-sm" name="descripcion" id="descripcion" rows="3" maxlength="256" disabled>[DESCRIPCION]</textarea>
						</div>
                        <div class="form-group custom-group">
							<label>Permiso Editable</label>
							<div class="input-group">
								<div class="input-group-addon">
									<input type="checkbox" id="editable" [CHECK] disabled>
                                    <label class="small" for="editable">Check para hacer el permiso editable</label>
								</div>
							</div>
						</div>
						<?php if ( $this->_acl->accesoVista("admin_acces") ) : ?>
						<div class="d-flex pb-2">
							<input type="hidden" name="token" id="token" value="[TOKEN]">
							<input type="hidden" name="id" id="id" value="[ID]">
							<button type="submit" class="btn btn-danger btn-sm btn-block mr-2">Eliminar Permiso</button>
							<a href="[URL_BASE]usuarios/permisos/listar" class="btn btn-warning btn-sm">Cancelar</a>
						</div>
						<?php endif; ?>
					</form>
				</div>
				<div class="col">
					<ul class="list-group">
						<li class="list-group-item list-group-item-danger"><small>Los <b>permisos</b> se usan en listas de control de acceso (ACL) para garantizar a un grupo de usuarios, o role, el acceso a ciertos recursos del sistema.<br>Existen tres permisos que el sistema trae por defecto que son: <b>Administración General</b>, <b>Tareas de Administración Local</b> y <b>Acceso General</b>. Estos permisos no se pueden editar<br>Un <b>Permiso</b> editable es aquel al que se le puede editar el nombre de este o su llave una vez creado y es la opción recomendada ante la creación de nuevos <b>Permisos</b></small></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>