<div class="jumbotron">
	<div class="container">
		<h1 class="display-3">Framework BlockPC</h1>
		<div class="estado" style="display:none;">
			<p>Estamos preparando la ultima versión. Lorem ipsum dolor sit amet, libero turpis non cras ligula, id commodo, aenean est in volutpat amet sodales, porttitor bibendum facilisi suspendisse, aliquam .......................</p>
			<span class="small float-right mt-1">[HOY]</span>
		</div>
		<div><a class="btn btn-primary btn-sm" href="[URL_ESTADO]" id="estado" role="button">Estado actual &raquo;</a></div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col">
			<h1>[TITULO] <small>[BROWSER]</small></h1>
		</div>
		<div class="col">
			<h1>[HOY]</h1>
		</div>
	</div>
</div>
