<h1><i class="fa fa-user" aria-hidden="true"></i> [SUBTITULO] | [ROLE]</h1>
<div class="table-responsive">
  <table class="table table-bordered table-sm table-hover">
    <caption>[ROLE]</caption>
    <thead class="table-info">
      <tr>
        <th scope="col">#
        <th scope="col">Llave
        <th scope="col">Permiso
        <th scope="col">Valor
    </thead>
    <tbody>
      [TBODY]
    </tbody>
  </table>
</div>