<section class="content-header">
    <h1><i class='fas fa-tachometer-alt mr-1'></i> Dashboard <small>[TITULO]</small></h1>
    <ol class="breadcrumb">
        <li><a class="text-success" href="/usuario/editar">Editar</a></li>
        <li><a href="#">[FECHA]</a></li>
    </ol>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-body">
			<div class="row">
				<div class="col">
					<ul id="directorio">[DIRECTORIO]</ul>
				</div>
				<div class="col">
					<pre class="small">[CLASES]</pre>
				</div>
			</div>
		</div>
	</div>
</section>