<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="icon" href="[RUTA_IMG]favicon.ico">
    <title>[TITULO] - [APP_NAME]</title>
    <link rel="stylesheet" href="[RUTA_CSS]bootstrap.min.css">
    <link rel="stylesheet" href="[RUTA_CSS]font-awesome.min.css">
    <link rel="stylesheet" href="[RUTA_CSS]AdminLTE.min.css">
    <link rel="stylesheet" href="[RUTA_CSS]skin-blue.min.css">
    <link rel="stylesheet" href="[RUTA_CSS]backend.css">
    <!-- Archivos CSS: para esta vista -->
	[VISTA_CSS]
</head>
<body class="hold-transition skin-blue sidebar-mini" id="page-top">
<noscript>Para utilizar las funcionalidades completas de este sitio es necesario tener JavaScript habilitado. Aquí están las <a href="https://www.enable-javascript.com/es/" target="_blank">instrucciones</a> para habilitar JavaScript en tu navegador web.</noscript>
    <div class="wrapper">
        <header class="main-header">
            <span class="logo">
                <span class="logo-mini"><img src="[RUTA_IMG]mini.png"></span>
                <span class="logo-lg"><b>[APP_NAME]</b><img class="ml-1" src="[RUTA_IMG]mini.png"></span>
            </span>
            <nav class="navbar navbar-static-top">
				<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
				<div class="navbar-custom-menu navbar-expand-sm">
                [MENU_PLANTILLA]
        <main class="content-wrapper">
            <div class="container-fluid">