        </div>
    </main>
    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            [APP_SISTEMA] <b>Versión</b> [APP_VERSION]
        </div>
        <strong>[APP_FECHA] <a href="https://www.blockpc.cl">blockpc.cl</a></strong>
    </footer>
</div>
<script src="[RUTA_JS]jquery.min.js"></script>
<script src="[RUTA_JS]jquery-ui.min.js"></script>
<script src="[RUTA_JS]popper.min.js"></script>
<script src="[RUTA_JS]bootstrap.min.js"></script>
<script src="[RUTA_JS]adminlte.min.js"></script>
<script src="[RUTA_JS]jquery.slimscroll.min.js"></script>
<script src="[RUTA_JS]backend.js"></script>
<!-- Archivos JS: para esta vista -->
[VISTA_JS]
</body>
</html>