<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"> <i class="fa fa-lock" aria-hidden="true"></i>[TITULO]</h1>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col">
      <table class="table table-sm table-hover table-bordered table-modal">
        <caption>Permisos básicos del framework</caption>
        <thead>
          <tr><th>#<th>Permiso<th>Llave<th>Editable
        </thead>
        <tbody>
        [PERMISOS]
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table table-sm table-hover table-bordered table-modal">
        <caption>Roles básicos del framework</caption>
        <thead>
          <tr><th>#<th>Role<th>Editable
        </thead>
        <tbody>
        [ROLES]
        </tbody>
      </table>
    </div>
  </div>
</div>