<table cellspacing="0" cellpadding="0" style="min-width: 600px;">
	<tr>
		<td colspan="2" style="padding: 10px; margin: 0 auto;"><img src="[RUTA_IMG]" width="100%" height="75"></td>
	</tr>
	<tr style="background-color: rgb(151, 191, 31); color: white;">
		<td style="padding: 5px; width: 20%;">Asunto:</td>
		<td style="padding: 5px; width: 80%;"><b>[ASUNTO]</b></td></td>
	</tr>
	<tr>
		<td style="padding: 5px; width: 20%;">Nombre </td>
		<td style="padding: 5px; width: 80%;">[NOMBRE]</td>
	</tr>
	<tr>
		<td style="padding: 5px; width: 20%;">Correo </td>
		<td style="padding: 5px; width: 80%;">[CORREO]</td>
	</tr>
	<tr>
		<td style="padding: 5px; width: 20%;">Mensaje</td>
		<td style="padding: 5px; width: 80%;">[MENSAJE]</td>
	</tr>
	<tr style="background-color: rgb(151, 191, 31); color: white; font-size: 12px;">
		<td style="padding: 5px; width: 20%;">Enviado el </td>
		<td style="padding: 5px; width: 80%;">[FECHA]</td>
	</tr>
</table>