<section class="content-header">
    <div class="topnav" id="myTopnav">
		<a class="first">[ICONO] [TITULO]</a>
		<a href="javascript:void(0);" class="icon" onclick="myFunction()">
			<i class="fa fa-bars"></i>
		</a>
		<a href="[URL_ACTIVOS]">Activos</a>
		<a href="[URL_NOACTIVOS]">No Activos</a>
		<a class="text-danger" href="[URL_ELIMINADOS]">Eliminados</a>
		<a class="last float-right d-none d-sm-block"><small>[FECHA]</small></a>
		<a class="float-right active-info text-info" href="[URL_NUEVO]">Nuevo Usuario</a>
	</div>
    <div class="row"><div class="col">[ERROR][MENSAJE]</div></div>
</section>
<section class="content">
	<div class="box box-info">
	</div>
</section>